### ISSUE TITLE
Sup

### ISSUE THREAD

**Issue by ravenspired** [MCPI-Revival/mcpi-MineTerm#1]
Very nice to see you working on a version, are you new to programming with Minecraft pi?

**Comment by leha-code** [comment]
I am not new.

**Comment by leha-code** [comment]
can we go to email? mine is pezleha@gmail.com . opening issues to each other is kind of dumb. well it does't make anything good, and we are just making our conversation seen to everyone

**Comment by leha-code** [comment]
Closed
